---@type table<string, string>
Flexible_unit_caps.lord_aliases = {
  --vcounts
  ["wh2_dlc11_vmp_bloodline_blood_dragon"] = "Blood_Dragon",
  ["wh_dlc05_vmp_red_duke"] = "Blood_Dragon",
  --elves
  ["wh2_main_hef_tyrion"] = "Hef_lord",
  ["wh2_dlc15_hef_archmage_beasts"] = "Hef_lord",
  ["wh2_dlc15_hef_archmage_death"] = "Hef_lord",
  ["wh2_dlc15_hef_archmage_fire"] = "Hef_lord",
  ["wh2_dlc15_hef_archmage_heavens"] = "Hef_lord",
  ["wh2_dlc15_hef_archmage_high"] = "Hef_lord",
  ["wh2_dlc15_hef_archmage_life"] = "Hef_lord",
  ["wh2_dlc15_hef_archmage_light"] = "Hef_lord",
  ["wh2_dlc15_hef_archmage_metal"] = "Hef_lord",
  ["wh2_dlc15_hef_archmage_shadows"] = "Hef_lord",
  ["wh2_main_hef_prince_caledor"] = "Hef_lord",
  ["AK_hef_seahelm"] = "Hef_lord",
  ["wh2_main_hef_prince"] = "Hef_lord",
  ["wh2_main_hef_princess"] = "Hef_lord",
  --lizards
  ["wh2_main_lzd_saurus_old_blood"] = "Lzd_lord",
  ["wh2_main_lzd_kroq_gar"] = "Lzd_lord",
  ["wh2_dlc13_lzd_gor_rok"] = "Lzd_lord",
  ["wh2_dlc12_lzd_tiktaqto"] = "Lzd_lord",
  ["wh2_dlc12_lzd_red_crested_skink_chief"] = "Skink",
  ["wh2_dlc12_lzd_red_crested_skink_chief_legendary"] = "Skink",
  ["wh2_dlc13_lzd_red_crested_skink_chief_horde"] = "Skink",
  ["wh2_dlc13_lzd_kroxigor_ancient"] = "Kroxi",
  ["wh2_dlc13_lzd_kroxigor_ancient_horde"] = "Kroxi",
  --vcoast
  ["wh2_dlc11_cst_admiral_fem"] = "Pirate",
  ["wh2_dlc11_cst_admiral_fem_death"] = "Pirate",
  ["wh2_dlc11_cst_admiral_fem_deep"] = "Pirate",
  ["wh2_dlc11_cst_admiral_tech_04"] = "Pirate",
  ["wh2_dlc11_cst_admiral"] = "Pirate",
  ["wh2_dlc11_cst_admiral_death"] = "Pirate",
  ["wh2_dlc11_cst_admiral_deep"] = "Pirate",
  ["wh2_dlc11_cst_admiral_tech_01"] = "Pirate",
  ["wh2_dlc11_cst_admiral_tech_02"] = "Pirate",
  ["wh2_dlc11_cst_admiral_tech_03"] = "Pirate",
  --Greenskin
  ["wh_main_grn_goblin_great_shaman"] = "Goblin",
  ["wh2_dlc15_grn_goblin_great_shaman_raknik"] = "Goblin",
  ["wh_dlc06_grn_night_goblin_warboss"] = "Goblin",
  ["wh_dlc06_grn_skarsnik"] = "Goblin",
  --Wood elves
  ["wh2_dlc16_wef_malicious_ancient_treeman_beasts"] = "Treeman",
  ["wh2_dlc16_wef_malicious_ancient_treeman_life"] = "Treeman",
  ["wh2_dlc16_wef_malicious_ancient_treeman_shadows"] = "Treeman",
  ["dlc05_wef_ancient_treeman"] = "Treeman",
  --Chaos dwarfs
  ["wh3_dlc23_chd_daemonsmith_sorcerer_death"] = "Daemonsmith",
  ["wh3_dlc23_chd_daemonsmith_sorcerer_fire"] = "Daemonsmith",
  ["wh3_dlc23_chd_daemonsmith_sorcerer_hashut"] = "Daemonsmith",
  ["wh3_dlc23_chd_daemonsmith_sorcerer_metal"] = "Daemonsmith",
  --Tomb kings
  ["wh2_dlc09_tmb_tomb_king"] = "tomb_king",
  ["wh2_dlc09_tmb_tomb_king_alkhazzar_ii"] = "tomb_king",
  ["wh2_dlc09_tmb_tomb_king_lahmizzash"] = "tomb_king",
  ["wh2_dlc09_tmb_tomb_king_rakhash"] = "tomb_king",
  ["wh2_dlc09_tmb_tomb_king_setep"] = "tomb_king",
  ["wh2_dlc09_tmb_tomb_king_thutep"] = "tomb_king",
  ["wh2_dlc09_tmb_tomb_king_wakhaf"] = "tomb_king",
}
